title = "Robin Zeng"
baseURL = "https://www.robinzen.com"
theme = "researcher"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]
enableEmoji = true

[params]
  author = "Robin Zeng"
  description = "Data-driven, mission-driven, "
  favicon = "favicon.ico"
  [params.footer]
    text = "Contact me!"
    url = "mailto:robinzeng1@gmail.com"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
